# Generated by Django 5.2.4 on 2025-08-09 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=200)),
                ('Roll_no', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_attendance.department')),
            ],
        ),
    ]
