# Generated by Django 5.2.4 on 2025-08-13 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='Year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_attendance.collegeyear'),
        ),
        migrations.CreateModel(
            name='YearSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(max_length=100)),
                ('Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_attendance.collegeyear')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaperName', models.CharField(max_length=300)),
                ('PaperCode', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=400, null=True)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_attendance.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_attendance.yearsemester')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='Semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_attendance.yearsemester'),
        ),
    ]
