# Generated by Django 5.2.4 on 2025-08-15 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0002_collegeyear_student_year_yearsemester_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Semester',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='Department',
        ),
        migrations.AddField(
            model_name='collegeyear',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_attendance.department'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_attendance.collegeyear'),
        ),
        migrations.DeleteModel(
            name='YearSemester',
        ),
    ]
