# Generated by Django 5.2.4 on 2025-08-15 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0003_remove_student_semester_remove_subjects_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_attendance.department'),
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_order', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_attendance.department')),
                ('Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_attendance.collegeyear')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_attendance.subjects')),
            ],
        ),
    ]
