# Generated by Django 5.2.4 on 2025-08-18 15:41

import student_attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0004_subjects_department_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=student_attendance.models.student_profile),
        ),
    ]
