# Generated by Django 5.2.4 on 2025-09-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0006_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='day_order',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
