# Generated by Django 5.2.4 on 2025-09-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0008_attendancesession_delete_attendance'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('student', 'date', 'login_time', 'logout_time'), name='unique_attendance_session'),
        ),
    ]
