# Generated by Django 5.2.4 on 2025-09-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0009_attendancesession_unique_attendance_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='Year',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
